version: 1
name: Total Queries
slug: queries-total-kpi
spaceSlug: oracle
tableName: query_analytics
updatedAt: "2026-02-21T00:00:00.000Z"

metricQuery:
  exploreName: query_analytics
  dimensions: []
  metrics:
    - query_analytics_total_queries
  filters: {}
  sorts: []
  limit: 1
  tableCalculations: []

chartConfig:
  type: big_number
  config:
    selectedField: query_analytics_total_queries
    label: Total Queries
    showBigNumberLabel: true
