version: 1
name: Total Volume
slug: total-volume-kpi
spaceSlug: oracle
tableName: market_overview
updatedAt: "2026-02-21T00:00:00.000Z"

metricQuery:
  exploreName: market_overview
  dimensions: []
  metrics:
    - market_overview_total_volume
  filters: {}
  sorts: []
  limit: 1
  tableCalculations: []

chartConfig:
  type: big_number
  config:
    selectedField: market_overview_total_volume
    label: Total Volume
    style: B
    showBigNumberLabel: true
